- README.md
fixed minor typo for rendering readme github markdown.
before,
after,
> fixed minor typo for rendering readme markdown.

- docs/documentation/docusaurus.config.js
Adds the permify playground link to the docs navbar. 
Closes #88
> Add permify playground link to navbar

- docs/documentation/docusaurus.config.js
Change the name of playground tab in top navbar
> Change the name of playground tab

- docs/documentation/docs/installation/brew.md
With v0.20 we deprecated the flag --database-pool-max, we use --max_open_connections instead.
> Fix deprecated flag --database-pool-max

- docs/documentation/docs/getting-started/modeling.md
- docs/documentation/docs/getting-started/sync-data.md
docs: update getting started sections
> docs: update getting started sections

- docs/documentation/docs/getting-started/modeling.md
- docs/documentation/docs/multi-tenancy.md
- docs/documentation/sidebars.js
- docs/documentation/src/components/Case/CaseList.jsx
Rename migration section, changed as Multi tenancy on v.0.4.0
> docs: rename  migration section

- docs/documentation/docs/api-overview.md
- docs/documentation/docs/api-overview/permission/check-api.md
docs: update api overview & latency
> docs: update api overview & latency

- docs/docs/getting-started/modeling.md
docs: fix the broken link in modeling section
> docs: fix the broken link in modeling section

- docs/docs/getting-started/enforcement.md
- docs/docs/getting-started/modeling.md
- docs/docs/getting-started/sync-data.md
- docs/docs/permify-overview/infrastructure.md
- docs/docs/permify-overview/intro.md
- docs/docusaurus.config.js
- docs/versioned_docs/version-0.2.x/permify-overview/intro.md
- docs/versioned_docs/version-0.3.x/permify-overview/intro.md
- docs/versioned_docs/version-0.4.x/permify-overview/intro.md
As I was going through the docs, I kept hitting broken links. This PR fixes some of them, but below is an extensive list:
https://docs.google.com/spreadsheets/d/1Fvob__PD6KSwvrISxpAoLdHf-d7P_youQUDhdrnTw10/edit?usp=sharing
If you are happy with the changes, I can continue on with the list. 
Fixes #806
> docs: fix broken links for overview and getting started pages

- docs/docs/api-overview.md
- docs/docs/api-overview/data/write-data.md
- docs/docs/api-overview/permission/check-api.md
- docs/docs/api-overview/permission/lookup-entity.md
- docs/docs/getting-started/enforcement.md
- docs/docs/installation/brew.md
- docs/docs/installation/overview.md
- docs/docs/playground.md
- docs/docs/reference/configuration.md
- docs/docs/reference/glossary.md
- docs/docs/reference/snap-tokens.md
- docs/docs/use-cases/custom-roles.md
- docs/docs/use-cases/multi-tenancy.md
- docs/src/components/Case/CaseList.jsx
This continues on from #848 to fix broken links in docs site. This PR addresses all broken links in the non-versioned docs.
Full list: https://docs.google.com/spreadsheets/d/1Fvob__PD6KSwvrISxpAoLdHf-d7P_youQUDhdrnTw10/edit?usp=sharing
> docs: fix all broken links in non-versioned docs

- docs/versioned_docs/version-0.3.x/api-overview.md
- docs/versioned_docs/version-0.3.x/api-overview/permission/check-api.md
- docs/versioned_docs/version-0.3.x/api-overview/relationship/write-relationships.md
- docs/versioned_docs/version-0.3.x/getting-started/enforcement.md
- docs/versioned_docs/version-0.3.x/getting-started/modeling.md
- docs/versioned_docs/version-0.3.x/getting-started/sync-data.md
- docs/versioned_docs/version-0.3.x/installation/brew.md
- docs/versioned_docs/version-0.3.x/installation/overview.md
- docs/versioned_docs/version-0.3.x/migrating.md
- docs/versioned_docs/version-0.3.x/permify-overview/infrastructure.md
- docs/versioned_docs/version-0.3.x/reference/glossary.md
- docs/versioned_docs/version-0.3.x/reference/snap-tokens.md
- docs/versioned_docs/version-0.3.x/use-cases/simple-rbac.md
This PR continues on fixing broken links in the docs website, this time all broken links for v0.3.x
Full list: https://docs.google.com/spreadsheets/d/1Fvob__PD6KSwvrISxpAoLdHf-d7P_youQUDhdrnTw10/edit?usp=sharing
> docs: fix broken links for versioned docs (v0.3.x)

- docs/docusaurus.config.js
With this PR readers can suggest changes to the docs with an easy to use WYSIWYG markdown editor.
[This](https://holocron.so/github/pr/Permify/permify/master/editor) is how the editor looks like for this repo.
https://github.com/remorses/docusaurus-example/assets/31321188/43c8bc68-3668-4a25-bf1c-a70eceab7bcb
> Added "Edit this page" link to docs

- internal/authn/preshared/authn.go
- internal/engines/balancer/balancer.go
As per [this](https://github.com/Permify/permify/issues/770) issue, this PR implements client-side authentication using pre-shared key.
I have not implemented OIDC authentication as yet since I need clarity on whether I'm moving in the right direction here.
Below are some links I read to understand pre-shared keys, OIDC and GRPC.
- https://en.wikipedia.org/wiki/Pre-shared_key
- https://pkg.go.dev/google.golang.org/grpc/credentials#PerRPCCredentials
- https://auth0.com/docs/authenticate/protocols/openid-connect-protocol#:~:text=OpenID%20Connect%20(OIDC)%20is%20an,to%20the%20OAuth%202.0%20specifications.
- https://grpc.io/docs/what-is-grpc/introduction/
> Implement Client-Side Authentication using Pre-shared Key

- docs/docs/bundle.md
docs: update data bundles content
> docs: update data bundles content

- pkg/cmd/coverage.go
fixes: #811
Description:
- calls validation before begining any computation on coverage.
- returns error if failed.
> feat(coverage): validating before running coverage.

- playground/src/layout/MainLayout.js
- playground/src/layout/components/GuidedTour.js
- playground/src/layout/sides/output.js
claim #933
Video walkthrough:
https://www.loom.com/share/ed24d9edd57740f09260572a2e204b89?sid=d606132c-6269-4f2f-a482-afe13fc6316b
> [feature] [playground] add guided tour

- Makefile
- playground/README.md
This updates the readme for playground to make it clearer on how to get the playground working locally as it wasn't very straight forward when I had to work on it.
> [playground] update docs for playground local dev

- docs/docs/reference/configuration.md
- docs/docs/reference/tracing.md
- example.config.yaml
- internal/config/config.go
- pkg/cmd/flags/serve.go
- pkg/cmd/serve.go
- pkg/telemetry/meterexporters/factory.go
- pkg/telemetry/meterexporters/otlp.go
- pkg/telemetry/tracerexporters/factory.go
- pkg/telemetry/tracerexporters/otlp.go
Allow to configure insecure for meters and tracing
Allow to define URL path for OTLP tracing
https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp#WithURLPath
> feat(tracing): Add meter-insecure, meter-urlpath, tracer-url-path configuration option

- docs/docs/reference/configuration.md
- pkg/cmd/flags/serve.go
This adds service config description for configuration as per #997 
I've done a parity check and made the following updates:
1. removed `service.relationship` this doesn't exist as an option
2. add flag and env binding for `service.permission.bulk_limit` as it is in the config & documentation but wasn't added as a flag
> docs: add service config description for configuration

- internal/factories/database.go
- internal/storage/migration.go
- internal/storage/postgres/utils/version.go
/claim #1009
This adds a helper function that's used to verify postgres version. The helper function is then used in 2 places:
1. Migrations (this doesn't panic, but logs out an error that migrations couldn't be run)
2. DatabaseFactory (this will cause a panic and exit)
> feat: error for unsupported psql versions

- .air.toml
- .gitignore
- Dockerfile.local
- Makefile
- docker-compose.yaml
Updated docker configs and added an air config for faster development. Air watches all the go files and rebuilds whenever there is any change in the code to reflect in the API immediately resulting in rapid prototyping and experimenting.
> chore: add air support for hot reloading

- internal/servers/server.go
- internal/storage/postgres/gc/gc.go
- pkg/cmd/serve.go
`slog.Error` does not support string formatting, so I have removed `%w` and `%v` from `slog.Error` lines.
If no key is provided, it prints `!BADKEY` to the console. To avoid that, I put a key before the variables.
> fix: `slog` `!BADKEY` errors

- docs/setting-up/configuration.mdx
This tiny PR fixes environment variable typo.
Thank you.
> docs: fix configuration database env

- internal/authn/oidc/authn.go
- internal/authn/oidc/authn_test.go
* Address race conditions with fetching JWKS with backoff retry logic
* Reduce concurrent calls to Refresh when multiple requests in retry logic concurrently
* Improve tests to validate number of retries and latency of authentication calls
* Prevent a successful KID that has not needed a refresh from resetting backoff retries
> feat(authn): improve jwks refresh retry mechanism

- docs/setting-up/configuration.mdx
This pull request fixes a spelling mistake in `docs/setting-up/configuration.mdx`. The term 'otpl' was corrected to 'otlp'.
Closes  #1392
> docs: correct spelling error in configuration.mdx

- docs/setting-up/installation/fly.mdx
Wanted to add to the documentation on how to get a container running Permify on Fly.io. The configuration is very basic at the moment and only gets the service running without persistent storage.
Hopefully I guessed correctly on where to add to the documentation 😅
Resolves #950
> docs: add documentation to deploy Permify as a Fly.io app

- docs/mint.json
- docs/setting-up/installation/fly.mdx
Configuration from initial docs creation for fly.io was causing errors when connecting via gRPC since the gRPC server for Permify terminates TLS for us.
Also adding fly.io docs to the side nav.
> fix(docs): update fly.io install instructions to allow connecting to gRPC service

- internal/storage/postgres/bundleReader_test.go
- internal/storage/postgres/bundleWriter_test.go
- internal/storage/postgres/consts.go
- internal/storage/postgres/dataReader_test.go
- internal/storage/postgres/dataWriter_test.go
- internal/storage/postgres/gc/gc_test.go
- internal/storage/postgres/instance/instance.go
- internal/storage/postgres/schemaReader_test.go
- internal/storage/postgres/schemaWriter_test.go
- internal/storage/postgres/tenantReader_test.go
- internal/storage/postgres/tenantWriter_test.go
- internal/storage/postgres/watch_test.go
This PR is created to eliminate any bugs may occur in the future as [Issue-1471](https://github.com/Permify/permify/issues/1471). 
I have added a garbage collector test under gc package. Here are the steps of the scenario:
- Set up the database connection and permission client before each test to ensure a clean environment.
- Create a new tenant to keep the data isolated.
- Write the schema to the database for the tenant.
- Insert and delete data, then perform permission checks to validate the state.
- Run the garbage collector to clean up any stale data.
Permission Validation: After each step (insertion, deletion, and GC), perform permission checks to confirm the expected state.
> feat: garbage collector test is added covering issue 1471
