Permify/permify

README.md

fixing readme markup, rendering image.

---

assets/content/API.md
assets/content/ENFORCEMENT.md
assets/content/SYNC.md

Create a content for data coordination and enforcement in Permify

Create SYNC.md & ENFORCEMENT.md

---

assets/content/MODEL.md
assets/content/SYNC.md

Changes made on SYNC.md about Change Data Capture approach. Also moved Zanzibar reference for data model to Model.md.

Updates on SYNC.md and MODEL.md

---

docs/documentation/docs/api-overview/check-api.md
docs/documentation/docs/getting-started/enforcement.md

Update enforcement section; remove the SQL query data filtering feature, add [/v1/permissions/lookup-entity-stream](https://app.swaggerhub.com/apis-docs/permify/permify/latest#/Permission/permissions.lookupEntityStream) and [/v1/permissions/lookup-entity](https://app.swaggerhub.com/apis-docs/permify/permify/latest#/Permission/permissions.lookupEntity) endpoints. Also fix the request and responses on the check API endpoint.

Update enforcement and check APIs

---

docs/documentation/docs/api-overview/_category_.json
docs/documentation/docs/deployment/_category_.json
docs/documentation/docs/deployment/aws.md
docs/documentation/docs/deployment/azure.md
docs/documentation/docs/deployment/google.md

Added pages shows how to deploy Permify on different infrastructure services in detail.

Add deployment patterns

---

docs/documentation/docs/getting-started/testing.md

Fix linking issue on [permify validate](https://github.com/Permify/permify-validate-action)

Fix linking issue on testing doc

---

docs/documentation/docs/api-overview/check-api.md
docs/documentation/docs/api-overview/expand-api.md
docs/documentation/docs/api-overview/schema-lookup.md
docs/documentation/docs/getting-started/enforcement.md
docs/documentation/docs/installation/overview.md

Add metadata body params on some endpoints

Add metadata body params on some endpoints

---

internal/repositories/postgres/relationshipReader.go
internal/repositories/postgres/relationshipWriter.go
internal/repositories/postgres/schemaReader.go
internal/repositories/postgres/schemaWriter.go
internal/services/relationshipService.go
internal/services/schemaService.go

#46  Adding deep tracing for relationships and schemas
This PR proposes changes to be made in order to incorporate the Deep Tracing Feature for Permify.
These changes make use of spans and spawning new spans where the request is forwarded to internal/commads, intenal/repositories and internal/services.

Adding deep tracing

---

docs/documentation/docs/deployment/aws.md

Fix image links on aws deployment

Fix image links on aws deployment

---

docs/documentation/docs/getting-started/enforcement.md

Fix body params in check request in enforcement section

Fix body params in check req

---

docs/documentation/docs/permify-overview/intro.md
docs/documentation/src/pages/index.js

Change the redirect path of the doc to the what is Permify

Update paths of docs/

---

docs/documentation/docusaurus.config.js

Change docs paht on sidebar.js

Change docs siderbar path

---

docs/documentation/docs/permify-overview/authorization-service.md
docs/documentation/docs/permify-overview/infrastructure.md
docs/documentation/docs/permify-overview/intro.md

Fix typos on overview section

---

docs/documentation/docs/getting-started/enforcement.md
docs/documentation/docs/getting-started/modeling.md
docs/documentation/docs/getting-started/sync-data.md
docs/documentation/docs/getting-started/testing.md

Fix typos in getting started

---

docs/documentation/docs/api-overview.md
docs/documentation/docs/api-overview/check-api.md
docs/documentation/docs/api-overview/delete-relationships.md
docs/documentation/docs/api-overview/expand-api.md
docs/documentation/docs/api-overview/read-api.md
docs/documentation/docs/api-overview/schema-lookup.md
docs/documentation/docs/api-overview/write-relationships.md
docs/documentation/docs/api-overview/write-schema.md
docs/documentation/sidebars.js

Add API clients to the docs

---

docs/documentation/docs/getting-started/modeling.md

Adding actions to another action like relations

Adding actions to another action

---

docs/documentation/docs/installation/container.md

Add meters to configuration options to configuration file in docs

Add meters to configuration options

---

docs/documentation/docs/installation/container.md

Update config yaml file

---

docs/documentation/docs/getting-started/sync-data.md
docs/documentation/docs/installation.mdx
docs/documentation/docs/installation/brew.md
docs/documentation/docs/installation/container.md
docs/documentation/docs/installation/overview.md
docs/documentation/src/components/Card/Card.jsx
docs/documentation/src/components/Card/CardList.jsx

Complete the new set up structure (2/2)

Complete the new set up structure (2/2)

---

docs/documentation/docs/api-overview.md
docs/documentation/docs/api-overview/write-relationships.md

Fix the params of some endpoints

Fix the params of some endpoints

---

docs/documentation/versioned_docs/version-0.2.x/api-overview/check-api.md

Fix linking issue

---

docs/documentation/docs/comparision.md
docs/documentation/sidebars.js

Add a page that shows comparision between other open source Zanzibar implementations

Add comparision page

---

docs/documentation/docs/api-overview/check-api.md
docs/documentation/docs/api-overview/lookup-entity.md
docs/documentation/sidebars.js

Add data filtering endpoints to api overview section

Add data filtering endpoints to api overview section

---

docs/documentation/docs/api-overview.md
docs/documentation/docs/comparision.md
docs/documentation/docs/getting-started/enforcement.md
docs/documentation/sidebars.js

Update api overview & enforcement section

Update api overview & enforcement section

---

docs/documentation/blog/2022-02-03-implementing-role-based-access-control-in-vue-js.md
docs/documentation/blog/2022-02-10-jwt-authentication-in-react.md
docs/documentation/blog/2022-02-28-cookie-management-in-expressjs-to-authenticate-users.md
docs/documentation/blog/2022-03-07-authentication-system-with-nodejs.md
docs/documentation/blog/2022-04-21-how-to-build-your-auth0-integration.md
docs/documentation/blog/2022-05-18-why-decouple-authorizations.md
docs/documentation/blog/2022-09-20-relational-based-access-control-models.md
docs/documentation/blog/2022-10-20-google-zanzibar-in-a-nutshell.md
docs/documentation/blog/2022-11-24-fine-grained-access-control-where-rbac-falls-short.md
docs/documentation/blog/2022-12-23-rbac-vs-rebac-when-to-use-them.md
docs/documentation/blog/2022-12-27-how-to-deploy-your-container-into-aws-ec2-with-ecs.md
docs/documentation/docusaurus.config.js
docs/documentation/package.json
docs/documentation/redirects.json
docs/documentation/sidebars.js
docs/documentation/yarn.lock

Move blogs to repo & handle redirects

Move blogs to repo & handle redirects

---

docs/documentation/blog/2023-01-22-team-permission-system-node-express-auth0.md
docs/documentation/docs/installation/container.md

Update the blog posts about auth0 and permify usage

Update the posts

---

docs/documentation/blog/2023-01-22-team-permission-system-node-express-auth0.md
docs/documentation/docs/api-overview.md
docs/documentation/docs/api-overview/permission/_category_.json
docs/documentation/docs/api-overview/permission/check-api.md
docs/documentation/docs/api-overview/permission/expand-api.md
docs/documentation/docs/api-overview/permission/lookup-entity.md
docs/documentation/docs/api-overview/permission/schema-lookup.md
docs/documentation/docs/api-overview/relationship/_category_.json
docs/documentation/docs/api-overview/relationship/delete-relationships.md
docs/documentation/docs/api-overview/relationship/read-api.md
docs/documentation/docs/api-overview/relationship/write-relationships.md
docs/documentation/docs/api-overview/schema/_category_.json
docs/documentation/docs/api-overview/schema/write-schema.md
docs/documentation/docs/api-overview/tenancy/_category_.json
docs/documentation/docs/api-overview/tenancy/tenancy-create.md
docs/documentation/docs/getting-started/enforcement.md
docs/documentation/docs/getting-started/sync-data.md
docs/documentation/docs/installation/brew.md
docs/documentation/docs/installation/container.md
docs/documentation/docs/installation/overview.md
docs/documentation/docs/reference/snap-tokens.md
docs/documentation/docusaurus.config.js
docs/documentation/sidebars.js
docs/documentation/src/pages/index.js
docs/documentation/versioned_docs/version-0.2.x/getting-started/enforcement.md
docs/documentation/versioned_docs/version-0.2.x/installation/overview.md
docs/documentation/versioned_docs/version-0.2.x/reference/snap-tokens.md

Update Docs & LP

---

docs/documentation/docs/getting-started/sync-data.md
docs/documentation/docs/migrating.md
docs/documentation/sidebars.js

Add migration section on docs

---

docs/documentation/blog/2023-01-21-team-permission-system-node-express-auth0-part-1.md
docs/documentation/blog/2023-01-22-team-permission-system-node-express-auth0-part-2.md
docs/documentation/package.json
docs/documentation/src/pages/index.js
docs/documentation/yarn.lock

Update head tags in LP

---

docs/documentation/blog/2023-01-21-team-permission-system-node-express-auth0-part-1.md
docs/documentation/blog/2023-01-22-team-permission-system-node-express-auth0-part-2.md
docs/documentation/docusaurus.config.js
docs/documentation/src/pages/index.js

Add blog cover to newest tutorial series

Add blog cover to newest tutorial series

---

docs/documentation/docusaurus.config.js

Disable API Reference in navbar

Disable API Reference section

---

docs/documentation/docs/api-overview/permission/expand-api.md

Update expand api content

---

docs/documentation/blog/2023-01-21-team-permission-system-node-express-auth0-part-1.md
docs/documentation/blog/2023-01-22-team-permission-system-node-express-auth0-part-2.md

Update latest blog posts

---

docs/documentation/docs/permify-overview/intro.md

Change the intro

---

docs/documentation/src/pages/index.js

Change fonts on landing page

---

internal/repositories/postgres/relationshipReader_test.go
internal/repositories/postgres/relationshipWriter.go
internal/repositories/postgres/relationshipWriter_test.go

- added test case for relationship writer postgresql.
- [issue](https://github.com/Permify/permify/issues/166)

TestCases: --added tests for reltion-writer

---

docs/documentation/docusaurus.config.js

Arrange the docs configuration

Arrange the docs configuration

---

docs/documentation/docs/installation/brew.md
docs/documentation/docs/installation/container.md

Update config flags & yaml file

Update config flags & yaml file

---

docs/documentation/docs/example-use-cases/nested-hierarchies.md
docs/documentation/docs/example-use-cases/organizational.md
docs/documentation/docs/example-use-cases/ownership.md
docs/documentation/docs/example-use-cases/parent-child.md
docs/documentation/docs/example-use-cases/sharing.md
docs/documentation/docs/example-use-cases/simple-rbac.md
docs/documentation/docs/example-use-cases/user-groups.md
docs/documentation/docs/getting-started/modeling.md
docs/documentation/sidebars.js

Add nested hierarhies use case to docs

Add nested hierarhies use case to docs

---

docs/documentation/docs/installation/container.md

Update the configuration glossary (1/8)

Update the configuration glossary (1/8)

---

docs/documentation/docs/installation/container.md

Update configuration glossary

---

docs/documentation/docs/installation/brew.md

Update Configuration Yaml file

Update Configuration Yaml file

---

docs/documentation/docs/getting-started/enforcement.md
docs/documentation/docs/installation/brew.md
docs/documentation/docs/installation/container.md

docs: add environment variables

docs: add environment variables

---

internal/servers/welcomeServer.go

fix: welcome json links

---

internal/servers/welcomeServer.go

fix: welcomeServer duplicated syntax

fix: welcomeServer duplicated syntax

---

docs/documentation/docs/permify-overview/intro.md

docs: change the overview intro

docs: change the overview intro

---

docs/documentation/docusaurus.config.js

docs: update the gtag

---

docs/documentation/docs/use-cases.md

docs: fix typos and improve content on use cases section

docs: fix typos and improve content on use cases section

---

docs/documentation/docs/api-overview/permission/expand-api.md
docs/documentation/docs/use-cases/organizational.md
docs/documentation/docs/use-cases/ownership.md
docs/documentation/docs/use-cases/sharing.md
docs/documentation/docs/use-cases/simple-rbac.md
docs/documentation/docs/use-cases/user-groups.md

docs: fix some typos and update language

docs: fix some typos and update language

---

docs/documentation/docs/api-overview/relationship/delete-relationships.md

docs: fix the deleteAPI node req

docs: fix the deleteAPI node req

---

docs/documentation/docusaurus.config.js

docs: update configuration analytics

docs: update configuration analytics

---

docs/documentation/docs/permify-overview/intro.md

docs: update the contribution guidelines

docs: update the contribution guidelines

---

docs/documentation/docs/getting-started/testing.md

docs: change the content in testing section

docs: change the content in testing section

---

docs/documentation/docs/api-overview/permission/lookup-entity.md
docs/documentation/docs/api-overview/permission/schema-lookup.md

docs: schema lookup & schema entity content fix

docs: schema lookup & schema entity content fix

---

Makefile
cmd/permify/permify.go
pkg/cmd/version.go

I was going through the repo and found this issue  #327.
I have created one PR for this. 
- I have made the changes in Makefile also.
- I was not sure about how to add the same on [.goreleaser.yml](https://github.com/Permify/permify/blob/master/.goreleaser.yml)
Can you guys please check and review it? Please let me know what changes I need to make.

feat: cli - version cmd

---

docs/documentation/docs/api-overview.md

docs: add authentication to api overview

docs: add authentication to api overview

---

docs/documentation/docs/permify-overview/intro.md

docs: add pricing plans to getting started

docs: add pricing plans to getting started

---

docs/documentation/docs/getting-started/modeling.md
docs/documentation/docs/installation/overview.md
docs/documentation/versioned_docs/version-0.2.x/getting-started/modeling.md
docs/documentation/versioned_docs/version-0.2.x/installation/overview.md
docs/documentation/versioned_sidebars/version-0.2.x-sidebars.json

docs: fix the link for usa cases

docs: fix the link for usa cases

---

docs/documentation/docs/getting-started/modeling.md

docs: update the modeling content

docs: update the modeling content

---

docs/documentation/docs/getting-started/sync-data.md

docs: update the managing authorization data section

docs: update the managing authorization data section

---

playground/src/App.js
playground/src/index.js
playground/src/layout/sides/authorizationData.js
playground/src/layout/sides/authorizationModel.js
playground/src/pkg/Editor/index.js

Improvement of error messages for better clarity and understanding.

Playground updates

---

docs/documentation/docs/permify-overview/intro.md

docs: add roadmap to the intro

---

pkg/cache/ristretto/ristretto_test.go
pkg/database/collections_test.go
pkg/database/iterators_test.go
pkg/database/pagination_test.go

Test improvements

---

docs/documentation/docs/getting-started/examples/google-docs.md

docs: add google docs style permission system (2/2)

docs: add google docs style permission system (2/2)

---

docs/documentation/docs/getting-started/examples/_category_.json
docs/documentation/docs/getting-started/examples/facebook-groups.md
docs/documentation/docs/getting-started/examples/google-docs.md
docs/documentation/package.json
docs/documentation/sidebars.js
docs/documentation/yarn.lock

docs: update google docs exp & add fb groups example

docs: update google docs exp & add fb groups example

---

docs/documentation/docs/getting-started/examples/notion.md
docs/documentation/sidebars.js

docs: add notion example model to examples (cont.)

docs: add notion example model to examples (cont.)

---

docs/documentation/docs/getting-started/examples/notion.md

docs: add notion example to real world examples

docs: add notion example to real world examples

---

docs/documentation/docs/getting-started/examples/facebook-groups.md
docs/documentation/docs/getting-started/examples/google-docs.md
docs/documentation/docs/getting-started/examples/notion.md

docs: fix contents in real world examples

docs: fix contents in real world examples

---

docs/documentation/docs/getting-started/examples/facebook-groups.md
docs/documentation/docs/getting-started/examples/google-docs.md
docs/documentation/docs/getting-started/examples/notion.md

docs: update contents on real world examples

docs: update contents on real world examples

---

docs/documentation/docs/installation/aws.md
docs/documentation/docs/installation/kubernetes.md

related to: #410 
Removed outdated `--database_name` flag.

docs: removed outdated db_name flag

---

docs/documentation/docusaurus.config.js
docs/documentation/package.json
docs/documentation/yarn.lock

related to #386 
Installed [docusaurus-search-local](https://github.com/cmfcmf/docusaurus-search-local) plugin for the search feature.

docs: docusaurus local search

---

docs/documentation/docs/getting-started/examples/facebook-groups.md
docs/documentation/docs/getting-started/examples/google-docs.md
docs/documentation/docs/getting-started/modeling.md
docs/documentation/src/css/custom.css

docs: update styling of the search button

docs: update styling of the search button

---

docs/documentation/docs/api-overview/schema/write-schema.md

docs: add suggested schema change workflow

docs: add suggested schema change workflow

---

docs/documentation/docs/installation/container.md

docs: minor explanation in docker deployment command

docs: minor explanation in docker deployment command

---

docs/documentation/docs/getting-started/sync-data.md
docs/documentation/docs/getting-started/testing.md
docs/documentation/docs/reference/snap-tokens.md
docs/documentation/sidebars.js

docs: update snap tokens & testing content

docs: update snap tokens & testing content

---

docs/documentation/docs/api-overview/watch/watch-changes.md
docs/documentation/sidebars.js

docs: change siderbar minor content

docs: change siderbar minor content

---

README.md

docs: update readme intro

---

docs/documentation/docs/getting-started/examples/notion.md

docs: fix content in notion example

docs: fix content in notion example

---

docs/documentation/docs/permify-overview/intro.md

docs: update introduction

---

docs/documentation/docs/reference/cache.md
docs/documentation/docs/reference/snap-tokens.md

docs: add cache mechanism section

docs: add cache mechanism section

---

docs/documentation/docs/reference/contextual-tuples.md

docs: update the contextual tuples section

docs: update the contextual tuples section

---

docs/documentation/docs/reference/contextual-tuples.md

docs: update the content of contextual tuple

docs: update the content of contextual tuple

---

docs/documentation/docs/api-overview/permission/check-api.md
docs/documentation/docs/getting-started/examples/google-docs.md
docs/documentation/docs/getting-started/testing.md

docs: update the depth field in check api

docs: update the depth field in check api

---

docs/documentation/docs/reference/configuration.md
docs/documentation/docs/reference/tracing.md
internal/config/config.go
pkg/cmd/serve.go
pkg/telemetry/tracerexporters/factory.go
pkg/telemetry/tracerexporters/otlp.go

Allow users to configure whether to use insecure conncetion for OTLP exporter.

feat(tracing): configurable security for otlp

---

docs/documentation/sidebars.js

docs: fix the page for cache mechanism

docs: fix the page for cache mechanism

---

docs/documentation/docs/reference/cache.md

docs: add consistent hashing operation details

docs: add consistent hashing operation details

---

docs/documentation/docs/api-overview/permission/lookup-entity.md

add how lookup operations evaluated section

docs:add how lookup operations evaluated section

---

docs/documentation/docs/api-overview/permission/check-api.md
docs/documentation/docs/api-overview/permission/lookup-entity.md
docs/documentation/docs/getting-started/enforcement.md
docs/documentation/docs/installation/overview.md

docs: change the getting started enforcement section

docs: change the getting started enforcement section

---

docs/documentation/docs/getting-started/modeling.md
docs/documentation/docs/use-cases/abac.md
docs/documentation/sidebars.js
docs/documentation/src/components/Case/CaseList.jsx

docs: add ABAC support to docs

docs: add ABAC support to docs

---

docs/documentation/docs/permify-overview/authorization-service.md

docs: improve grammar

---

docs/documentation/docs/getting-started/modeling.md
docs/documentation/docs/use-cases/abac.md

docs: release abac support

---

internal/config/config_test.go

fix: fixed deprecated package usage in `config_test.go`

---

internal/config/config_test.go

* Test coverage increased from **50%** to **83.3%** in `config.go`.

test: increase test coverage from 50% to 83.3%

---

docs/documentation/docs/api-overview.md

docs: update the api overview section

docs: update the api overview section

---

docs/documentation/docs/playground.md

docs: update playground section

docs: update playground section

---

docs/documentation/docs/getting-started/testing.md
docs/documentation/docs/playground.md
docs/documentation/sidebars.js

docs: update testing section & playground test scenario

docs: update testing section & playground test scenario

---

playground/src/layout/sides/enforcement.js

refactor(playground): change the guidline color in enforcement

refactor(playground): change the guidline color in enforcement

---

docs/documentation/docs/api-overview/permission/check-api.md
docs/documentation/docs/getting-started/enforcement.md
docs/documentation/docs/use-cases/abac.md
docs/documentation/docs/use-cases/multi-tenancy.md

docs: fix links

---

docs/docs/installation/brew.md
docs/docs/installation/container.md
docs/docs/permify-overview/intro.md

- typo and grammar cleanup in the main intro doc

docs: cleanup grammar and typos

---

docs/docs/api-overview/data/delete-data.md
docs/docs/api-overview/data/read-attributes.md
docs/docs/api-overview/data/write-data.md
docs/docs/api-overview/permission/check-api.md
docs/docs/api-overview/permission/expand-api.md
docs/docs/api-overview/permission/lookup-entity.md
docs/docs/api-overview/permission/lookup-subject.md
docs/docs/api-overview/permission/subject-permission.md
docs/docs/api-overview/schema/write-schema.md
docs/docs/api-overview/tenancy/create-tenant.md
docs/docs/api-overview/tenancy/delete-tenant.md
docs/docs/api-overview/watch/watch-changes.md

docs: upgrade the api services

docs: upgrade the api services

---

docs/src/components/Card/CardList.jsx

docs: fix the links in the installation page

docs: fix the links in the installation page

---

docs/docs/getting-started/examples/instagram.md
docs/sidebars.js

docs: added real life example of instagram authorizaton schema. 

---

docs/docs/api-overview/schema/write-schema.md
docs/docs/getting-started/enforcement.md
docs/docs/getting-started/modeling.md
docs/docs/getting-started/sync-data.md
docs/docs/installation/overview.md
docs/docs/permify-overview/authorization-service.md
docs/docs/permify-overview/infrastructure.md
docs/docs/permify-overview/intro.md
docs/docs/reference/configuration.md
docs/docs/reference/glossary.md
docs/docs/use-cases/multi-tenancy.md

docs: update the content on introduction sections & remove WriteDB keyword

docs: update the content on introduction sections & remove WriteDB keyword

---

docs/docs/getting-started/examples/instagram.md
docs/docs/getting-started/examples/mercury.md
docs/sidebars.js

docs: added new example of Mercury Authorization Schema.

---

docs/docs/getting-started/modeling.md

docs: update the modeling guide

docs: update the modeling guide

---

internal/storage/postgres/dataReader.go
internal/storage/postgres/dataWriter.go
internal/storage/postgres/schemaReader.go
internal/storage/postgres/schemaWriter.go
internal/storage/postgres/tenantReader.go
internal/storage/postgres/tenantWriter.go
internal/storage/postgres/watch.go

resolving issue #836 
I have incorporated logging in the `internal/storage/postgres/dataReader.go` file. Kindly review the format, and inform me if any modifications are necessary. Additionally, I would appreciate confirmation that I am following the correct approach.

feat: added logs for postgres.

---

CONTRIBUTING.md
README.md

Hi 👋 
I'm new around here, and noticed there were a few typos in Readme & Contributing doc. 
I have also made a few suggestions other than typos that improve the flow of sentences and/or fix grammar issues. 
Disclaimer: I'm not a native English speaker, but have been living in UK for more than a decade :)

docs: grammar improvements in contributing and readme

---

pkg/cmd/validate.go
pkg/schema/loader.go
pkg/schema/loader_test.go
pkg/schema/schema.txt

Adds SchemaLoader to load schema over HTTP, Fs Path
https://github.com/Permify/permify/assets/62795688/decb9cef-637f-4deb-af70-523efb425bba
/claim #840
/closes #840

feat: add schema loader

---

docs/docs/getting-started/modeling.md

docs: add the recursive ReBAC section to modeling section

docs: add the recursive ReBAC section to modeling section

---

docs/docs/playground.md

docs: update the playground section on docs

docs: update the playground section on docs

---

docs/versioned_docs/version-0.4.x/api-overview.md
docs/versioned_docs/version-0.4.x/api-overview/permission/check-api.md
docs/versioned_docs/version-0.4.x/api-overview/relationship/write-relationships.md
docs/versioned_docs/version-0.4.x/getting-started/enforcement.md
docs/versioned_docs/version-0.4.x/getting-started/modeling.md
docs/versioned_docs/version-0.4.x/getting-started/sync-data.md
docs/versioned_docs/version-0.4.x/installation/brew.md
docs/versioned_docs/version-0.4.x/installation/overview.md
docs/versioned_docs/version-0.4.x/permify-overview/infrastructure.md
docs/versioned_docs/version-0.4.x/playground.md
docs/versioned_docs/version-0.4.x/reference/configuration.md
docs/versioned_docs/version-0.4.x/reference/glossary.md
docs/versioned_docs/version-0.4.x/reference/snap-tokens.md
docs/versioned_docs/version-0.4.x/use-cases/custom-roles.md
docs/versioned_docs/version-0.4.x/use-cases/multi-tenancy.md

This continues fixing of broken links. 
The PR fixes all broken links for v0.4.x 
full list: https://docs.google.com/spreadsheets/d/1Fvob__PD6KSwvrISxpAoLdHf-d7P_youQUDhdrnTw10/edit?usp=sharing

docs: fix broken links for v0.4.x

---

docs/README.md
docs/docs/api-overview/permission/check-api.md
docs/docs/installation.md
docs/docs/permify-overview/intro.md
docs/docs/use-cases.md
docs/docusaurus.config.js
docs/versioned_docs/version-0.2.x/getting-started/enforcement.md
docs/versioned_docs/version-0.2.x/permify-overview/intro.md
docs/versioned_docs/version-0.3.x/getting-started/enforcement.md
docs/versioned_docs/version-0.3.x/installation.md
docs/versioned_docs/version-0.3.x/permify-overview/intro.md
docs/versioned_docs/version-0.3.x/use-cases.md
docs/versioned_docs/version-0.4.x/api-overview/permission/check-api.md
docs/versioned_docs/version-0.4.x/installation.md
docs/versioned_docs/version-0.4.x/permify-overview/intro.md
docs/versioned_docs/version-0.4.x/use-cases.md

docs: update discord invitation link

docs: update discord invitation link

---

CONTRIBUTING.md
README.md
internal/info.go

refactor: update discord invitation link

refactor: update discord invitation link

---

docs/docs/getting-started/enforcement.md

docs: updated the enforcement section

docs: updated the enforcement section

---

docs/docs/api-overview/data/write-data.md
docs/docs/api-overview/permission/check-api.md
docs/docs/api-overview/permission/expand-api.md
docs/docs/api-overview/permission/lookup-entity.md
docs/docs/api-overview/permission/lookup-subject.md
docs/docs/api-overview/permission/subject-permission.md
docs/docs/reference/contextual-tuples.md

docs: update write data section  & update contextual data section & fix broken links

docs: update write data section  & update contextual data section & fix broken links

---

docs/docs/api-overview.md

docs: Add Error Codes in documentation

---

docs/docs/api-overview/bundle/write-bundle.md
docs/docs/data-bundles.md
docs/sidebars.js

docs: udpate bundle service sections content

docs: udpate bundle service sections content

---

docs/docs/bundle.md

docs: fix broken link in bundle section

docs: fix broken link in bundle section

---

docs/docs/api-overview/permission/lookup-entity.md

docs: fix style in lookup entity content

docs: fix style in lookup entity content

---

internal/config/config.go
pkg/cmd/flags/serve.go
pkg/cmd/serve.go

feat: add JSON logging

---

docs/docs/reference/configuration.md
pkg/cmd/serve.go

docs: add log ouput, refactor: default log output

---

playground/src/layout/sides/particials/data/attributes.js
playground/src/layout/sides/particials/data/relationships.js

Fix: Button Alignment Issue in Playground 

---

internal/servers/bundleServer.go
internal/servers/dataServer.go
internal/servers/permissionServer.go
internal/servers/schemaServer.go

/close #955
1. Some of apis return 500 error code, even though the issue is on client side/not found.
1. Changed files in `servers` folder
- moving validation errors and not found errors  to `status.Error` using implemented func `GetStatus`

enhancement: meaningful errors

---

docs/docs/getting-started/modeling.md

docs: minor update on modeling section

docs: minor update on modeling section

---

docs/sidebars.js

docs: add read & list schema endpoints to sidebar

docs: add read & list schema endpoints to sidebar

---

pkg/cmd/serve.go

fix: #1092

---

README.md

docs: fixed the urls according to the new doc

docs: fixed the urls according to the new doc

---

docs/mint.json

docs: add dark as the default mode

docs: add dark as the default mode

---

docs/api-reference/introduction.mdx
docs/docs/permify-overview/authorization-service.md
docs/docs/permify-overview/intro.md
docs/docs/playground.md
docs/getting-started/enforcement.mdx
docs/getting-started/examples/facebook-groups.mdx
docs/getting-started/examples/google-docs.mdx
docs/getting-started/examples/notion.mdx
docs/getting-started/quickstart.mdx
docs/getting-started/testing.mdx
docs/operations/cache.mdx
docs/operations/contextual-tuples.mdx
docs/permify-overview/authorization-service.mdx
docs/permify-overview/intro.mdx
docs/setting-up/installation/aws.mdx
docs/setting-up/installation/brew.mdx
docs/setting-up/installation/container.mdx
docs/setting-up/installation/google.mdx
docs/use-cases/abac.mdx
docs/use-cases/custom-roles.mdx
docs/use-cases/multi-tenancy.mdx
docs/use-cases/rbac.mdx
docs/use-cases/rebac.mdx

docs: change the meeting links

docs: change the meeting links

---

docs/mint.json
docs/operations/partial-schema-update.mdx
docs/permify-overview/intro.mdx

docs: add partial schema update docs page

docs: add partial schema update docs page

---

docs/api-reference/introduction.mdx
docs/docs/permify-overview/authorization-service.md
docs/docs/permify-overview/intro.md
docs/docs/playground.md
docs/getting-started/enforcement.mdx
docs/getting-started/examples/facebook-groups.mdx
docs/getting-started/examples/google-docs.mdx
docs/getting-started/examples/notion.mdx
docs/getting-started/quickstart.mdx
docs/getting-started/testing.mdx
docs/operations/cache.mdx
docs/operations/contextual-tuples.mdx
docs/permify-overview/authorization-service.mdx
docs/permify-overview/intro.mdx
docs/setting-up/installation/aws.mdx
docs/setting-up/installation/brew.mdx
docs/setting-up/installation/container.mdx
docs/setting-up/installation/google.mdx
docs/use-cases/abac.mdx
docs/use-cases/custom-roles.mdx
docs/use-cases/multi-tenancy.mdx
docs/use-cases/rbac.mdx
docs/use-cases/rebac.mdx

docs: add meeting links in docs

docs: add meeting links in docs

---

docs/api-reference/permission/check-api.mdx
docs/getting-started/enforcement.mdx

docs: add abac context data example check request

docs: add abac context data example check request

---

docs/docs/permify-overview/authorization-service.md

docs:update authorization as a service section

docs:update authorization as a service section

---

docs/permify-overview/authorization-service.mdx

docs:change the sidebar title of Authorization As A Service section

docs:change the sidebar title of Authorization As A Service section

---

pkg/cmd/serve.go

- lowered file and directory permissions

fix: file permissions updated

---

internal/engines/cache/cache.go
internal/servers/dataServer.go
internal/servers/schemaServer.go
internal/servers/server.go
pkg/telemetry/meter.go

- added metric exporters for data and schema servers

feat: metric exporters for data and schema servers

---

.github/workflows/sdk-generator.yml

- removed api naming to fix init import errors

fix: update sdk-generator.yml

---

docs/cloud/intro.mdx
docs/mint.json

docs: added permify cloud overview

docs: added permify cloud overview

---

docs/mint.json

docs: change cloud sidebar title

docs: change cloud sidebar title

---

docs/mint.json
docs/products/cloud.mdx

docs: create products group and move cloud intro there

docs: create products group and move cloud intro there

---

docs/mint.json

docs: add tabs openapi field in mint.json

docs: add tabs openapi field in mint.json

---

docs/mint.json

docs: remove tabs openapi field in mint.json

docs: remove tabs openapi field in mint.json

---

docs/api-reference/apidocs.swagger.json

docs: adjust apiswaggerdocs for docs

docs: adjust apiswaggerdocs for docs

---

docs/mint.json

docs: fix the url in api reference

docs: fix the url in api reference

---

README.md

docs: remove the open jobs section

docs: remove the open jobs section

---

docs/api-reference/openapi.json
docs/mint.json

docs: changes for openapi json

docs: changes for openapi json

---

docs/api-reference/introduction.mdx
docs/getting-started/enforcement.mdx

docs: added new SDK clients links to docs

docs: added new SDK clients links to docs
